### ISSUE TITLE
Basic Structure of the app 

### ISSUE THREAD

**Issue by Hannes-HH** [Hannes-HH/capstone-project#1]
## Value Statement 

As a user of the app I will have a great usability. And a good overview of the various landing pages. 

## Acceptance Criteria 
- [] (navbar should be placed in header)
- [] (navbar should be always visible)
- [] (it should be responsive)

## Tasks 
- [] (create the navbar)
- [] (create components)
- [] (add css)
- [] (make them responsive)
