### ISSUE TITLE
Create React Router 

### ISSUE THREAD

**Issue by Hannes-HH** [Hannes-HH/capstone-project#2]
## Value Statement

As a user of the app I will have a great navigation throw the app and clarity. 

## Acceptance Criteria

- [ ] the 1st Link shows the new releases 
- [ ] the 2nd Link shows an overview of all films and series

## Tasks

- [ ] (install react router dom)
- [ ] (import BrowserRouter)
- [ ] (build navBar component)
- [ ] (build page components)
- [ ] (build header component)
